first

diff --git a/tools/taskfiles/taskfile_dev.yml b/tools/taskfiles/taskfile_dev.yml
--- a/tools/taskfiles/taskfile_dev.yml
+++ b/tools/taskfiles/taskfile_dev.yml
@@ -70,7 +70,11 @@ tasks:
 
   poetry-lock:
     desc: Lock dependencies in metapkg
+    vars:
+      POETRY_VERSION:
+        sh: cat .poetry-version
     cmds:
+      - poetry self update {{.POETRY_VERSION}}
       - poetry lock --no-update --directory={{.METAPKG_DIR}}
     requires:
       vars:
@@ -84,6 +88,49 @@ tasks:
     requires:
       vars:
         - VENV_PATH
+
+  _run-for-each-lib:
+    desc: Run command for each library
+    cmds:
+      - |
+        exit_code=0;
+        command_status=0;
+        for LIB_PATH in $LIB_PATHS; do
+          ITERATION_COMMAND=${COMMAND//%s/$LIB_PATH};
+          echo "Going to run '$ITERATION_COMMAND'";
+          set +e;
+          eval $ITERATION_COMMAND || command_status=$?;
+          set -e;
+          if [ $command_status -ne 0 ]; then
+            echo "Command failed with exit status $command_status";
+            exit_code=$command_status;
+          fi;
+          if [ $FAIL_FAST == "true" ] && [ $exit_code -ne 0 ]; then
+            echo "FAIL_FAST is true and command failed, breaking";
+            break;
+          fi
+        done;
+        exit $exit_code;
+    env:
+      FAIL_FAST: '{{.FAIL_FAST | default "true"}}'
+      COMMAND: '{{.COMMAND}}'
+      LIB_PATHS:
+        sh: |
+          find "{{.USER_WORKING_DIR}}" -name 'pyproject.toml' \
+            | sort \
+            | xargs -n1 realpath \
+            | xargs -n1 dirname \
+            {{ if .EXCLUDE_LIB_PATHS -}}
+              {{- range $i, $path := .EXCLUDE_LIB_PATHS | splitLines -}}
+                {{- if ne $path "" }} | grep -v "^{{$path}}$" {{ end -}}
+              {{- end -}}
+            {{- end -}}
+
+  poetry:
+    desc: Run poetry command
+    dir: "{{.USER_WORKING_DIR}}"
+    cmds:
+      - poetry --directory={{.PYPROJECT_TOML_PATH}} {{.CLI_ARGS}}
 
   venv-python:
     desc: Run poetry command
@@ -119,7 +166,79 @@ tasks:
           find {{.CLI_ARGS | default "."}} -name 'pyproject.toml' \
           | sort \
           | xargs -n1 realpath \
+          {{ if .EXCLUDE_TOML_SORT -}}
+            {{- range $i, $path := .EXCLUDE_TOML_SORT | splitLines -}}
+              {{- if ne $path "" }} | grep -v "^{{$path}}$" {{ end -}}
+            {{- end -}}
+          {{- end -}}
           | tr '\n' ' '
+
+  _deptry:
+    desc: Run deptry on package
+    requires:
+      vars:
+        - LIB_PATH
+    cmds:
+      - echo "Running deptry checks for {{.LIB_PATH}}"
+      - task: venv-python
+        vars:
+          DIR: "{{.LIB_PATH}}"
+          CLI_ARGS: |
+            deptry . \
+              --exclude ".*tests"
+
+  _deptry-tests-dependencies:
+    desc: Run deptry on tests dependencies
+    requires:
+      vars:
+        - LIB_PATH
+    cmds:
+      - echo "Running deptry checks for testing dependencies for {{.LIB_PATH}}"
+      - |
+        if grep -q '\[tool\.poetry\.group\.tests\.dependencies\]' {{.LIB_PATH}}/pyproject.toml; then
+          sed -i.backup '/^\[tool\.poetry\.group\.tests\.dependencies\]/d' {{.LIB_PATH}}/pyproject.toml
+        else
+          echo "No tests dependencies found in {{.LIB_PATH}}/pyproject.toml";
+        fi
+      - defer: |
+          if [ -f {{.LIB_PATH}}/pyproject.toml.backup ]; then
+            mv {{.LIB_PATH}}/pyproject.toml.backup {{.LIB_PATH}}/pyproject.toml
+          fi
+      - task: venv-python
+        vars:
+          DIR: "{{.LIB_PATH}}"
+          CLI_ARGS: |
+            deptry .
+
+  deptry:
+    desc: Run deptry
+    cmds:
+      - task: _run-for-each-lib
+        vars:
+          COMMAND: 'task dev:_deptry LIB_PATH=%s'
+      - task: _run-for-each-lib
+        vars:
+          COMMAND: 'task dev:_deptry-tests-dependencies LIB_PATH=%s'
+
+  _mypy:
+    desc: Run mypy on package
+    requires:
+      vars:
+        - LIB_PATH
+    cmds:
+      - echo "Running mypy checks for {{.LIB_PATH}}"
+      - task: venv-python
+        vars:
+          DIR: "{{.LIB_PATH}}"
+          CLI_ARGS: |
+            mypy .
+
+  mypy:
+    desc: Run mypy
+    cmds:
+      - task: _run-for-each-lib
+        vars:
+          COMMAND: 'task dev:_mypy LIB_PATH=%s'
 
   lint:
     desc: Lint code
@@ -144,24 +263,11 @@ tasks:
         vars:
           FIX: 'false'
 
-      - for: { var: LIB_PATHS, as: LIB_PATH }
-        task: _deptry
-        vars:
-          LIB_PATH: '{{.LIB_PATH}}'
+      - task: deptry
 
-      - for: { var: LIB_PATHS, as: LIB_PATH }
-        task: _mypy
-        vars:
-          LIB_PATH: '{{.LIB_PATH}}'
+      - task: mypy
     vars:
       LINT_PATH: '{{.CLI_ARGS | default "."}}'
-      LIB_PATHS:
-        sh: |
-          find {{.CLI_ARGS | default "."}} -name 'pyproject.toml' \
-            | sort \
-            | xargs -n1 realpath \
-            | xargs -n1 dirname \
-            {{ range $i, $path := .EXCLUDE_LIB_PATHS | splitLines }} | grep -v "^{{$path}}$" {{end}}
 
   lint-fix:
     desc: Lint fix code
@@ -186,51 +292,11 @@ tasks:
         vars:
           FIX: 'true'
 
-      - for: { var: LIB_PATHS, as: LIB_PATH }
-        task: _deptry
-        vars:
-          LIB_PATH: '{{.LIB_PATH}}'
+      - task: deptry
 
-      - for: { var: LIB_PATHS, as: LIB_PATH }
-        task: _mypy
-        vars:
-          LIB_PATH: '{{.LIB_PATH}}'
+      - task: mypy
     vars:
       LINT_PATH: '{{.CLI_ARGS | default "."}}'
-      LIB_PATHS:
-        sh: |
-          find {{.CLI_ARGS | default "."}} -name 'pyproject.toml' \
-            | sort \
-            | xargs -n1 realpath \
-            | xargs -n1 dirname \
-            {{ range $i, $path := .EXCLUDE_LIB_PATHS | splitLines }} | grep -v "^{{$path}}$" {{end}}
-
-  _deptry:
-    desc: Run deptry on package
-    requires:
-      vars:
-        - LIB_PATH
-    cmds:
-      - echo "Running deptry checks for {{.LIB_PATH}}"
-      - task: venv-python
-        vars:
-          DIR: "{{.LIB_PATH}}"
-          CLI_ARGS: |
-            deptry . \
-              --exclude ".*tests"
-
-  _mypy:
-    desc: Run mypy on package
-    requires:
-      vars:
-        - LIB_PATH
-    cmds:
-      - echo "Running mypy checks for {{.LIB_PATH}}"
-      - task: venv-python
-        vars:
-          DIR: "{{.LIB_PATH}}"
-          CLI_ARGS: |
-            mypy .
 
   test:
     desc: Run tests
@@ -403,3 +469,18 @@ tasks:
       - echo "Next processes will be killed:"
       - ps -ef | grep "ssh -f -N -L" | grep --invert-match "grep"
       - pkill -f "ssh -f -N -L"
+
+  squash:
+    desc: Squash all commits made on CHILD_BRANCH relative to PARENT_BRANCH into single one (using git reset --soft)
+    vars:
+      REMOTE: '{{.REMOTE | default "origin"}}'
+    requires:
+      vars:
+        - PARENT_BRANCH
+        - CHILD_BRANCH
+    cmds:
+      - git fetch {{.REMOTE}} -f {{.PARENT_BRANCH}}:{{.PARENT_BRANCH}}
+      - git switch {{.CHILD_BRANCH}}
+      - git fetch {{.REMOTE}} {{.CHILD_BRANCH}}
+      - git reset --soft $(git merge-base {{.PARENT_BRANCH}} HEAD)
+      - echo 'Now you can commit merged changes with "git commit -m "commit message"'
